# server specific
server:
  port: 8080
  jetty:
    connection-idle-timeout: 20s
    threads:
      max: 10
      min: 3
      idle-timeout: 30000ms
    max-http-form-post-size: 5MB
    accesslog:
      retention-period: 7
  shutdown: graceful
  servlet:
    session:
      timeout: 20m
      cookie:
        http-only: true
    application-display-name: domain-api
  compression:
    enabled: true
    min-response-size: 2KB # default value
    mime-types: "text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, application/xml, image/jpeg, image/png, application/octet-stream"
  error:
    whitelabel:
      enabled: false

# spring specific
spring:
  main:
    lazy-initialization: true
    web-application-type: servlet
    banner-mode: off
  jackson:
    time-zone: UTC
    locale: en_US
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/domain?currentSchema=domain"
    username: "user"
    password: "P@55w0rd"
    initialization-mode: never
    hikari:
      minimumIdle: 5
      maximumPoolSize: 21
      autoCommit: false
      connection-timeout: 1000
      pool-name: "hikari-pool"
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: "jdbc:postgresql://localhost:5432/domain"
    user: "user"
    password: "P@55w0rd"
    connect-retries: 3
    schemas: "domain"
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        default_schema: "domain"
    show-sql: true
  mvc:
    format:
      date: iso
      date-time: iso
  lifecycle:
    timeout-per-shutdown-phase: 30s
  messages:
    cache-duration: 3600
    basename: messages/messages

# actuator specific
management:
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true
  endpoint:
    health:
      enabled: true
      probes.enabled: true
      show-components: never
      show-details: never
      group:
        readiness:
          include: readinessState, db
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: "*"
  metrics.export.prometheus.enabled: true

# logging specific
logging.level:
  ROOT: info
  com.demo: info
  org.springframework: info

# spring doc specific
springdoc:
  show-actuator: true
  swagger-ui:
    path: /api/v1/domain-service/swagger-ui.html
  api-docs:
    path: /api/v1/domain-service/apidocs
